In [25]:
%%file simpleTest.c
#include <stdio.h>

int main() {
    int a = 7;
    printf("Hello\n");
    printf("num is %d\n", a);
    //fflush(stdout);

    return 0;
}

/*
 compile in python kernel:
 !gcc test_simple.c -o simpleTest
 To run : !simpleTest
*/

Overwriting simpleTest.c


In [13]:
!gcc simpleTest.c -o simpleTest

In [9]:
!simpleTest

Hello
num is 7


In [1]:
#Simple test: Qiskit calls C 

import subprocess
from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

print("Qiskit , C test\n")

#compile C 
subprocess.run (["gcc" , "simpleTest.c" , "-o" , "simpleTest"])
#Run C 
result = subprocess.run(["./simpleTest"] , capture_output = True, text = True)
print(result.stdout)
#Parse C output
lines = result.stdout.strip().split('\n')
numValue = int(lines[1].split()[-1])

print(f"Extracted value: {numValue}\n")


#creating quantum circuit
print("creating quantum circuit\n")
qc = QuantumCircuit(3,3)

if numValue > 8 : 
    print(f"Value {numValue} > 8, add x gate ")
    qc.x([0,1,2])
else:
    print("adding hadmard gate")
    qc.h([0,1,2])

qc.measure([0,1,2] , [0,1,2])

#run sim 
print("running quantum sim")
simulator = AerSimulator()
job = simulator.run(qc, shots=10)
counts = job.result().get_counts()

#results
print("\nResults:")
for bitstring, count in sorted(counts.items()):
    print(f"  {bitstring}: {count}")

print("Integration works")



Qiskit , C test

Hello
num is 7

Extracted value: 7

creating quantum circuit

adding hadmard gate
running quantum sim

Results:
  000: 1
  001: 1
  010: 2
  011: 1
  100: 3
  101: 1
  110: 1
Integration works


In [1]:
%%writefile matrix_test.c
#include <stdio.h>

int main() {
    FILE *file = fopen("matrix.txt", "w");
    
    // Create a 3x3 matrix
    int matrix[3][3] = {
        {1, 2, 3},
        {4, 5, 6},
        {7, 8, 9}
    };
    
    // Write dimensions
    fprintf(file, "3,3\n");
    
    // Write matrix values
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            fprintf(file, "%d", matrix[i][j]);
            if (j < 2) fprintf(file, ",");
        }
        fprintf(file, "\n");
    }
    
    fclose(file);
    printf("Matrix written to matrix.txt\n");
    return 0;
}

Writing matrix_test.c


In [3]:
import subprocess
import numpy as np

# Compile and run C program
print("Compiling C program...")
subprocess.run(["gcc", "matrix_test.c", "-o", "matrix_test"])

print("Running C program...\n")
subprocess.run(["./matrix_test"])

# Read matrix from file
print("\nReading matrix from file...")
with open("matrix.txt", "r") as f:
    lines = f.readlines()
    
    rows, cols = map(int, lines[0].strip().split(','))
    
    matrix = []
    #header not included
    for i in range(1, rows + 1):
        row = list(map(int, lines[i].strip().split(',')))
        matrix.append(row)

matrix = np.array(matrix)
transposed = matrix.T

print("\nOriginal Matrix (from C):")
print(matrix)

print("\nTransposed Matrix (by Python):")
print(transposed)

print("\n Matrix integration test done!")

Compiling C program...
Running C program...


Reading matrix from file...

Original Matrix (from C):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix (by Python):
[[1 4 7]
 [2 5 8]
 [3 6 9]]

 Matrix integration test done!
